SiLeBAT/zoonotify-client

src/app/Main/Body/QueryPage/Drawer/Displayed_Features/Drawer-GraphSettings.component.tsx, src/app/Main/Body/QueryPage/Drawer/Displayed_Features/Table-Selector.component.tsx, src/app/Main/Body/QueryPage/Drawer/Drawer-Layout.component.tsx, src/app/Main/Body/QueryPage/Drawer/Drawer-Resize.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/Drawer-FilterSettings.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/Filter-Selector.component.tsx, src/app/Main/Body/QueryPage/QueryPage.component.tsx
Ticket: #82
Change-Id: I75b802f8f5188fb398914372c5d297965517683e
=> Adjust the Drawer to any size

src/app/Main/Body/QueryPage/QueryPage-Content.component.tsx, src/app/Main/Body/QueryPage/QueryPage-TextContent.component.tsx, src/app/Main/Body/QueryPage/Results/QueryPage-ResultData.component.tsx, src/app/Main/Body/QueryPage/Results/Results-Table.component.tsx
- use full space for large tables
- handle overflow
Ticket: #83
Change-Id: Ief05d76978a4455fe7ba357e4c1acfd5940c3892
=> Change size of result table

src/app/Main/Body/Body-Router.component.tsx, src/app/Main/Body/InfoPage/InfoPage.component.tsx, src/app/Main/Header/Header.component.tsx, src/app/Shared/URLs.ts, src/locales/de/Header.json, src/locales/de/InfoPage.json, src/locales/en/Header.json, src/locales/en/InfoPage.json
- Add info-page
- Add navigation
Ticket: #89
Change-Id: I988f45eab9360e41e7e58ef7b1ad6d4bb52b876a
=> REBASE Add page for more infomation about the data

src/app/Main/Header/Header.component.tsx
Ticket: #112
Change-Id: I585c6fd2a6fd054c9796cf4be9c8d80dcc72ba95
=> Close gab between tab and action bar

src/app/Main/Body/QueryPage/Drawer/Displayed_Features/Drawer-GraphSettings.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/Drawer-FilterSettings.component.tsx, src/app/Shared/ClearSelectorButton.component.tsx
- size
- position
- align to heading
Ticket: #113
Change-Id: I455f305eeeb579560baae20a221b7a86024389d7
=> Change remove-buttons style

src/app/Main/Body/QueryPage/Results/QueryPage-ResultData.component.tsx, src/app/Main/Body/QueryPage/Results/Results-Table.component.tsx, src/app/Main/Body/QueryPage/Results/Results-TableHeader.component.tsx, src/app/Main/Body/QueryPage/Results/Results-TableRows.component.tsx
- add vertical separtor lines
- Text alignment in table header to the right
- no line break in "Anzahl isolate"
Ticket: #122
Change-Id: I95f5afc33728e1f5931f79673079acbeed72065e
=> Change table style

src/locales/de/Header.json, src/locales/de/InfoPage.json
Ticket: #121
Change-Id: I5b22a912688de4eb69c0793936b35ab31455bdb5
=> Change "Erklärungen" to "Erläuterungen"

src/app/Main/Body/QueryPage/Parameter/Parameter-List.component.tsx, src/app/Main/Body/QueryPage/Results/Results-Table.component.tsx, src/app/Main/Body/QueryPage/Results/Results-TableHeader.component.tsx
- change letter-spacing
- change in parameter box and in table
Ticket: #114
Change-Id: If93b398340c9ef8170d1ed3b5d3770fcb1142d60
=> Unify the distance between the letters

src/app/Core/ExportServices/generateParameterHeader.service.ts
Ticket: #116
Change-Id: I653e57cc414178fa91240d1410001aa15fff5e91
=> Change header in export-files

src/app/Main/Header/Export/Export-ActionButtons.component.tsx, src/app/Main/Header/Export/Header-Export.component.tsx, src/app/Main/Header/Export/Header-ExportButton.component.tsx
- remove unused "open"-prop
Ticket: #140
Change-Id: Ia38c22649c018d5e34491ae70cccc6d8d5df948b
=> Close dialog window after clicking Export

.eslintignore, cypress/integration/language.spec.ts, cypress/integration/navigation.spec.ts, src/app/__tests__/sum.test.ts, tsconfig.json
Ticket: #148
Change-Id: Id3d000a20cc6d658f512997d1cd528d6fea7298b
=> Debug cypress & eslint

src/app/Main/Body/QueryPage/Drawer/Displayed_Features/Drawer-GraphSettings.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/Drawer-FilterSettings.component.tsx, src/app/Shared/ClearSelectorButton.component.tsx, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json, tsconfig.json
Ticket: #123
Change-Id: I3ce79cd534e60cf284178a3216b4b80afc38a873
=> Implement mouse-over for the remove button

src/app/Main/Body/QueryPage/Results/QueryPage-ResultData.component.tsx, src/app/Main/Body/QueryPage/Results/Results-Table.component.tsx, src/app/Main/Body/QueryPage/Results/Results-TableHeader.component.tsx, src/app/Main/Body/QueryPage/Results/Results-TableRows.component.tsx
- missing commas
- wrong import
- wrong border color
Ticket: #117
Change-Id: I6be29d916e14fdfd41efaa4d65c5b23438101d06
=> Debug Ticket 117 (wrong merge)

src/app/Main/Body/Body-Router.component.tsx, src/app/Main/Body/LinkPage/LinkPage-List.component.tsx, src/app/Main/Body/LinkPage/LinkPage-ListContent.component.tsx, src/app/Main/Body/LinkPage/LinkPage-ListItem.component.tsx, src/app/Main/Body/LinkPage/LinkPage.component.tsx, src/app/Main/Header/Header.component.tsx, src/app/Shared/URLs.ts, src/assets/external_links.json, src/locales/de/ExternLinks.json, src/locales/de/Header.json, src/locales/en/ExternLinks.json, src/locales/en/Header.json
- Implement navigation
- Write JSON with link-information
- Implement list with JSON input
- Use translation
Ticket: #50
Change-Id: If9cd02b6c3e7869454db91a13f65a3006edc469a
=> Implement page for external links

src/app/Main/Body/QueryPage/QueryPage-Content.component.tsx, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
Ticket: # 156
Change-Id: I93ef81135bd4e927423ed5a767d8ad204c3b9b31
=> Add information about data status

src/app/Main/Body/HomePage/HomePage.component.tsx, src/app/Main/Footer/Footer-Layout.component.tsx, src/app/Main/Footer/Footer-Links.component.tsx, src/app/Main/Footer/LastUpdate-Date.component.tsx
Ticket: #168
Change-Id: Ie5266faa8c3ce0b6d54f3073aecf15f3ed9801f4
=> Adjust the footer to one line at laptop size

src/app/Main/Body/QueryPage/NumberOfIsolates/QueryPage-NrOfIsolates.component.tsx, src/app/Main/Body/QueryPage/NumberOfIsolates/countNrOfIsolates.component.ts, src/app/Main/Body/QueryPage/Parameter/QueryPage-ParameterContent.component.tsx, src/app/Main/Body/QueryPage/QueryPage-Content.component.tsx, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
- count isolates (total and selected)
Ticket: #160
Change-Id: I9b5564046ec9a4e4909602f64e92a8be583aa8b9
=> Add accordion with number of isolates

src/app/Main/Body/QueryPage/Results/Result-MainHeader.component.tsx
Ticket: #159
Change-Id: I23e3a7a87d9fc05b7e1a7933e2d2e9a416a3ff54
=> Change table style to dark blue

src/app/Main/Body/QueryPage/QueryPage-Content.component.tsx, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
Ticket: #162
Change-Id: I803e07b442c13c4f5ffecd5927e8d025f287a528
=> Remove Devider and Result-Heading

src/app/Main/Body/QueryPage/Parameter/Parameter-List.component.tsx, src/app/Main/Body/QueryPage/Parameter/QueryPage-ParameterContent.component.tsx
- remove table
Ticket: #169
Change-Id: I60b37de8e15880b580f9aa5062fd8c94a83a1d96
=> Display Parameter in two columns

src/app/Main/Body/QueryPage/Results/QueryPage-ResultData.component.tsx, src/app/Main/Body/QueryPage/Results/Result-Content.component.tsx, src/app/Main/Body/QueryPage/Results/Results-Table.component.tsx, src/app/Main/Body/QueryPage/Results/Results-TableHeader.component.tsx, src/app/Main/Body/QueryPage/Results/Results-TableRows.component.tsx, src/app/Shared/ExplanationText.component.tsx, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
- move Table from "ResultData" to "Content" component
- remove check isIsolates from table styling
Ticket: #167
Change-Id: Id3d520d8a135e04588f8b22ab693b67037e50187
=> Explanation Text if no row/column selected

src/app/Main/Body/QueryPage/Results/TableResults/TableResults-TableMainHeader.component.tsx
Ticket: #186
Change-Id: I14ab85063e267ea46964fd6b233a416b82014eaf
=> Remove light blue border of table main header

src/app/Main/Body/QueryPage/QueryPage-Content.component.tsx
Ticket: #185
Change-Id: Ib362aa8e1adb28ccd3beb018dd9c0d1aa8714171
=> Add space on top of table accordion

src/app/Core/ExportServices/dataAndStatisticToZipFile.service.ts, src/app/Core/ExportServices/generateExportLabels.service.ts, src/app/Core/ExportServices/generateParameterHeader.service.ts, src/app/Core/ExportServices/parameterAndDataToCsvString.service.ts, src/app/Core/FilterServices/checkIfFilterIsSet.service.ts, src/app/Core/FilterServices/filterData.service.ts, src/app/Core/generatePathString.service.ts, src/app/Core/getFilterFromPath.service.ts, src/app/Main/Body/QueryPage/Drawer/Displayed_Features/DisplFeatures-Selector.component.tsx, src/app/Main/Body/QueryPage/Drawer/Displayed_Features/Drawer-DisplFeatures.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/Drawer-Filter.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/Filter-SelectorList.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/SelectorList-Selector.component.tsx, src/app/Main/Body/QueryPage/Parameter/QueryPage-ParameterContent.component.tsx, src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx, src/app/Main/Body/QueryPage/QueryPage-Content.component.tsx, src/app/Main/Body/QueryPage/Results/Content-Results.component.tsx, src/app/Main/Header/Export/Export-ActionButtons.component.tsx, src/app/Main/Header/Export/Header-Export.component.tsx, src/app/Shared/ClearSelectorButton.component.tsx, src/app/Shared/Context/DataContext.tsx, src/app/Shared/Context/FilterContext.tsx, src/app/Shared/Model/Filter.model.ts, src/app/Shared/URLs.ts, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
- possibility to save mainFilter
- separate selected Filter
Ticket: #108
Change-Id: Iaf83cbffc87bd5fd15a7178af97a2827913eb374
=> Use filterconfig API

src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
Ticket: #184
Change-Id: If2c2dfe9ecb2a66b311e29d9067f014fa2ce576f
=> Change drawer heading

src/locales/de/ExternLinks.json, src/locales/en/ExternLinks.json
Ticket: #195
Change-Id: I4ef7e229bb092749e49863ced3dbf0ca772793ad
=> Change text on page with external links

src/app/Core/ExportServices/dataAndStatisticToZipFile.service.ts, src/app/Core/ExportServices/generateCSVString.service.ts, src/app/Core/ExportServices/generateDataString.service.ts, src/app/Core/ExportServices/generateFilteredDataString.service.ts, src/app/Core/ExportServices/generateParameterHeader.service.ts, src/app/Core/ExportServices/generateRAWString.service.ts, src/app/Core/ExportServices/parameterAndDataToCsvString.service.ts, src/app/Core/FilterServices/filterData.service.ts, src/app/Main/Body/QueryPage/Drawer/Filter/Drawer-Filter.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/SelectorList-Selector.component.tsx, src/app/Main/Body/QueryPage/Parameter/QueryPage-ParameterContent.component.tsx, src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx, src/app/Main/Body/QueryPage/Results/Content-Results.component.tsx, src/app/Main/Body/QueryPage/Results/Results-RowsWithIsolates.service.ts, src/app/Main/Body/QueryPage/Results/TableResults/Results-TableResults.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableResults-Options.component.tsx, src/app/Main/Header/Export/Export-ActionButtons.component.tsx, src/app/Main/Header/Export/Header-Export.component.tsx, src/app/Shared/ClearSelectorButton.component.tsx, src/app/Shared/Context/DataContext.tsx, src/app/Shared/Context/FilterContext.tsx, src/app/Shared/Model/Api_Isolate.model.ts, src/app/Shared/Model/Client_Isolate.model.ts, src/app/Shared/Model/Export.model.ts, src/app/Shared/Model/Filter.model.ts, src/app/Shared/Model/Isolate.model.ts, src/app/Shared/Selector.component.tsx, src/app/Shared/URLs.ts, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
Ticket: #199
Change-Id: I07494d560616718c95f5005be8ca7a30eb3eca2a
=> Use isolates form API and change model types

src/app/Main/Body/QueryPage/Drawer/Displayed_Features/DisplFeatures-Selector.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/SelectorList-Selector.component.tsx, src/app/Shared/Selector.component.tsx
Ticket: #204
Change-Id: I242df01d6ddd9d0b94433e18f0e1ce01cdad8247
=> Change label of selectors for displayed features

src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx
Ticket: #208
Change-Id: Id9855b267b3a9d8940eb945cf2d4530321242b45
=> Debug loading Filter from URL

src/app/Core/generatePathString.service.ts, src/app/Core/getFilterFromPath.service.ts
- ?matrix=bob_kate => ?matrix=bob&matrix=kate
Ticket: #198
Change-Id: I1ee58b72526d16251acc9f061abcfa655c26978e
=> Modify format of url-path

src/locales/de/ErrorPage.json
Ticket: #222
Change-Id: Ib16481e6f2ed10f6a4313205715bf1e6dd8a9212
=> Remove typo in ErrorPage

src/app/Main/Footer/Footer-LinkList.component.tsx
Change-Id: Icf054a7eac5f986c609c0c5709142cb1523d9396
Ticket: #226
=> Remove unnecessary footer links

src/app/Main/Body/QueryPage/Results/TableResults/TableContent-Rows.component.tsx
Ticket: #230
Change-Id: Icc65982988903a63129b06dc9ae83f6cfa89f412
=> Add Lodash import

src/app/Main/Body/QueryPage/DatabaseStatusIndicator/QueryPage-DatabaseStatusIndicator.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent-Layout.component.tsx, src/app/Shared/Model/Api_Database.model.ts, src/app/Shared/URLs.ts, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
Change-Id: Ia618c86eb4f760c9dfa58bc35ad81a20a122d8b3
Ticket: #220
=> Retrieve Database status from the server

package-lock.json, src/locales/de/ErrorPage.json
Change-Id: Idc9085e2144b9813be339b6d7239a420d10e13e3
Ticket: #229
=> Fix spelling mistake in Error Page

src/app/Shared/Selector.component.tsx
Ticket: #218
Change-Id: I9c21e027baf9fa4afe58566cbf3a1d004bff52c2
=> Limit height of selector dropdown

src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx, src/app/Main/Body/QueryPage/QueryPage-Layout.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent-Layout.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/QueryPageContent-TableResultsLayout.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/ResultsTable.style.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableContent-Header.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableContent-RowWithColSums.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableContent-Rows.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableContent-Table.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableResults-Options.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableResults-TableContent.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableResults-TableMainHeader.component.tsx, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
Ticket: #196
Change-Id: I6c5293381d5d76cb79979fe5718b2692864ec7d6
=> Implementing col and row sum for the table

src/app/Main/Footer/Footer-Container.component.tsx, src/app/Main/Footer/Footer-Layout.component.tsx, src/app/Main/Footer/Footer-LinkList.component.tsx, src/app/Main/Header/Header.component.tsx, src/app/Main/Main-Layout.component.tsx, src/app/Shared/Model/Api_Info.model.ts, src/app/Shared/URLs.ts, src/locales/de/Footer.json, src/locales/en/Footer.json
Ticket: #245
Change-Id: I419138be7e6112f1ce7c7053a7ed44a4fa9f834a
=> Use support mail from api

src/app/Main/Body/QueryPage/Results/TableResults/TableContent-Header.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableContent-Table.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableResults-TableContent.component.tsx, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
Ticket: #217
Change-Id: I7dd1dbabde90add6e8bf56d46188ec5fabb1957c
=> Add unit (%) to table header

src/app/Main/Body/QueryPage/Results/Charts/QueryPageContent-BarChart.component.tsx
Ticket: #262
Change-Id: I193c22e3c8d6be9597d8a2a9d50e0b6679cac588
=> Add defaultExpanded props to BarChart-Accordion

tsconfig.json
Ticket: #265
Change-Id: I49d12db65494cb1c90cb64aae0fb3460b19e98fe
=> Set "allowUmdGlobalAccess" true in tsconfig

src/app/Main/Footer/Footer-LinkList.component.tsx
Change-Id: Ic1e6517c081e6c54b0a09c4536607b0925e90062
Ticket: #269
=> Add link to API documentation to footer

src/app/Main/Header/Export/Header-ExportContainer.component.tsx
Ticket: #273
Change-Id: I3a44e4207190b353ada1ea0ffd4426eb9c9b2481
=> Close Dialog after ZIP Export

src/app/Main/Body/QueryPage/Results/Charts/QueryPageContent-BarChart.component.tsx, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
Ticket: #277
Change-Id: I60bc74f8bb34c964f9ea6a7915593893b1282311
=> Add translation & axis to feature selectors

src/app/Main/Body/QueryPage/Results/Charts/QueryPageContent-BarChart.component.tsx
Ticket: #279
Change-Id: I5aa646a87fe79e1780eaa4943492a92f47e27610
=> Center Chart accordion content

src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
Ticket: #289
Change-Id: Idbc31df1474371f313c57b3feb0e4a6aa317982c
=> Renaming in "Anzahl Isolate" Accordion

src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx, src/app/Main/Body/QueryPage/QueryPageServices/TableServices/calculateRelativeTableData.service.ts, src/app/Main/Body/QueryPage/Results/TableResults/QueryPageContent-TableResultsLayout.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableContent-Header.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableContent-Table.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableResults-TableContent.component.tsx, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
Ticket: #286
Change-Id: I53ea5a4d26ab898974347d8d02d3e51e52c1e7cb
=> Change "Anzahl Isolate" text if data is relative

src/app/Main/Body/QueryPage/Results/TableResults/TableContent-Rows.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableContent-Table.component.tsx
Ticket: #293
Change-Id: I39fdc00ed8765affcabba0329cf6a50c821d3d05
=> Make row content dependant of col header

src/app/Main/Body/QueryPage/Drawer/Filter/Dialog/FilterDialog-SelectAllButton.component.tsx, src/locales/de/QueryPage.json
Ticket: #285
Change-Id: I9caede30175752279a867679573082a7b7d20d4a
=> Change style & text of select/deselect all buttons

src/app/Main/Body/InfoPage/Amrs/InfoPage-AmrsContent.component.tsx, src/locales/de/InfoPage.json, src/locales/en/InfoPage.json
Ticket: #284
Change-Id: Ie1fdb5f279700e8236b7a8387c18b5c1433d1c18
=> Add EUCAST Link

src/app/Main/Body/InfoPage/InfoPage-Container.component.tsx
Ticket: #283
Change-Id: I9ea4c31d69151d85c069b6b1eca05de267867bde
=> Add information's to table export

src/app/Main/Body/InfoPage/Amrs/InfoPage-AmrsDialog.component.tsx
Ticket: #306
Change-Id: I7a5ed502747450be12d33eefc960451bf61b056f
=> Increase font size of explanation tables

src/assets/external_links.json, src/locales/de/ExternLinks.json, src/locales/en/ExternLinks.json
Ticket: #248
Change-Id: I870acc82250641cdfcf2b740febb727b055226de
=> Add more external links

package-lock.json, package.json, src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx, src/app/Main/Body/QueryPage/QueryPage-Layout.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent-Layout.component.tsx, src/app/Main/Body/QueryPage/Results/Charts/BarChartResults.component.tsx, src/app/Main/Body/QueryPage/Results/Charts/QueryPageContent-BarChart.component.tsx
Ticket: #34
Change-Id: Iee30eac980626288233edf72c01ebec494221257
=> Implement external Button to download chart

src/app/Main/Body/QueryPage/QueryPageContent-Layout.component.tsx, src/app/Main/Body/QueryPage/Results/Charts/BarChartResults.component.tsx, src/app/Main/Body/QueryPage/Results/Charts/QueryPageContent-BarChart.component.tsx, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
Ticket: #281
Change-Id: Id66421068b4658ae11bcad50f93a34bcf0c1be1d
=> Add axis labels

src/app/Main/Body/QueryPage/Drawer/Drawer-Layout.component.tsx, src/app/Main/Body/QueryPage/Parameter/ParameterContent-List.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent-Layout.component.tsx, src/app/Main/Main-Layout.component.tsx
- sticky footer
- scrolling behavior QueryPage
- remove useless css
Ticket: #239
Change-Id: I29516e6e50cc69168a008978918456d3d2b35c68
=> Change style

src/app/Main/Body/QueryPage/QueryPageContent-Layout.component.tsx
Ticket: #327
Change-Id: If8baa2edfb9509f92bb09189032a17026f6e1c99
=> Add missing </div>

src/app/Main/Header/Export/ExportServices/DataExportServices/generateDataRowsCsvString.service.ts, src/app/Main/Header/Export/ExportServices/DataExportServices/generateDataTableCsvString.service.ts, src/app/Shared/Model/Client_Isolate.model.ts
Ticket: #240
Change-Id: Ib89ae0a55e67faffc2b5df9d75214790dea12237
=> Display resistances with 1/0 in export table

src/app/Shared/Selector.component.tsx
Ticket: #305
Change-Id: I966b7ce773fe9c73d8fee00209048ee59d919578
=> Adapt closeMenuOnSelect prop of selector

src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx, src/app/Main/Body/QueryPage/Results/Charts/BarChartResults.component.tsx, src/app/Main/Body/QueryPage/Results/Charts/QueryPageContent-BarChart.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableContent-Header.component.tsx, src/app/Main/Body/QueryPage/Results/TableResults/TableContent-Rows.component.tsx, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
Ticket: #288
Change-Id: Ie8d9e6e1381211cef155900eed625574661fd9c0
=> Display chart data in relative numbers

src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx, src/app/Main/Header/Export/ExportServices/dataAndStatisticToZipFile.service.ts, src/app/Main/Header/Export/Header-ExportContainer.component.tsx, src/app/Shared/Model/Client_Isolate.model.ts
Ticket #253
Change-Id: Ie3874463a219b60b8dae746d71f95e1a4b1c32b8
=> Change order of main filters

src/app/Main/Body/QueryPage/Results/TableResults/TableContent-RowWithColSums.component.tsx
Ticket: #287
Change-Id: Iffde29f4a66ff06c8711e14c2e8ba70a48cc9ad6
=> Add total sum to Table

src/app/Main/Body/QueryPage/Results/Charts/QueryPageContent-BarChart.component.tsx
Ticket: #319
Change-Id: I26493898491bf4cedc46036a206bee2c4e579fff
=> Fix grow/shrink of chart

package-lock.json, package.json, src/app/Main/Header/Export/Header-ExportContainer.component.tsx
Ticket: #275
Change-Id: I5188b4749a16c016b795377bf6de2bf5e1935e24
=> Remove info about row/col from isolate url

src/app/Main/Body/QueryPage/Drawer/Displayed_Features/DisplFeatures-Selector.component.tsx, src/app/Main/Body/QueryPage/Drawer/Drawer-Layout.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/Drawer-Filter.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/Filter-SelectorList.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/SelectorList-Selector.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/SubFilter-Selector.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/generateSelectorObject.service.ts, src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx, src/app/Main/Body/QueryPage/QueryPage-Layout.component.tsx, src/app/Main/Body/QueryPage/Services/adaptFilterFromAPI.service.ts, src/app/Shared/Context/FilterContext.tsx, src/app/Shared/Model/Api_Filter.model.ts, src/app/Shared/Model/Client_Isolate.model.ts, src/app/Shared/Model/Filter.model.ts, src/app/Shared/Selector.component.tsx, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
Ticket: #351
Change-Id: If4b1250a4ed01da1af3c8b5d26c64d1c38692fd2
=> Implement SubFilter

src/app/Main/Body/QueryPage/Results/Charts/BarChartResults.component.tsx, src/app/Main/Body/QueryPage/Results/Charts/QueryPageContent-BarChart.component.tsx
Ticket: #342
Change-Id: I3c30a7cbbc6e1ef6a9a9e5b049786f6dd91bc183
=> Change chart type to stacked if data is relative

src/app/Main/Body/DataProtectionPage/DataProtection.config.ts, src/app/Main/Body/DataProtectionPage/DataProtectionPage.component.tsx, src/locales/de/DataProtection.json, src/locales/en/DataProtection.json
Ticket: #350
Change-Id: I5f3a98bfa709055fe3d0782c8a0e915ebe6b7f7b
=> Change contact details "Datenschutzbeauftragte"

src/app/Main/Footer/Footer-LinkList.component.tsx, src/app/Shared/URLs.ts
Change-Id: I61b8ea612c8b31b72d1a35bc46b148252c481868
Ticket: #355
=> Remove API-documentation link from footer

src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx
Ticket: #367
Change-Id: I6cf1c89c94580cbe3eeb6058a80790153c201bc5
=> Fetch conditional filter values if new filter value is set

src/app/Main/Body/QueryPage/Drawer/Displayed_Features/Drawer-DisplFeatures.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/Drawer-Filter.component.tsx, src/app/Shared/ClearSelectorButton.component.tsx
Ticket: #373
Change-Id: I30cc61cc5ed0ce8aae8a76e50f7a0f6247581841
=> Disable "deselect all" button if data is loading

src/app/Shared/Model/Client_Isolate.model.ts
Ticket: #378
Change-Id: I6a42ebb81e14fc1a27473a81cb563fefed15f985
=> Remove "resistance" key from mainFilterList

src/locales/en/QueryPage.json
Ticket: #343
Change-Id: I0dadf23ad16df56d6eae2798841e3c33e7c53c9b
=> Typos in english translation

src/app/App.tsx, src/app/Main/Body/QueryPage/Drawer/Drawer-Layout.component.tsx, src/app/Shared/ClearSelectorButton.component.tsx
Ticket: #388
Change-Id: If90433757336eef261c783a496c4fb96dd878227
=> Change drawer position to relative

src/app/Main/Body/QueryPage/Drawer/ControlBar/QueryPage-DrawerControl.component.tsx
Ticket: #395
Change-Id: Iba3eba82b0a1e6103d137601257c8c327cdb1928
=> Set the transition to a definite unit.

src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx, src/app/Main/Body/QueryPage/Services/ContainerServices/fetchConditionalFilters.service.tsx
=> Define URLParams new for each parameter

src/app/Main/Footer/Footer-Layout.component.tsx, src/app/Main/Footer/Footer-LinkList.component.tsx, src/app/Main/Footer/LastUpdate-Date.component.tsx, src/app/Main/Footer/LastUpdate-Version.component.tsx, src/app/Main/Footer/LastUpdate.component.tsx
=> Refactor styles in Footer components

src/app/Shared/Dialog.component.tsx
=> Change loading circle style in export button

src/app/Main/Footer/Footer-LinkList.component.tsx
=> Fix footer padding

src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx, src/app/Main/Body/QueryPage/Services/ContainerServices/exportZip.service.tsx, src/app/Shared/LoadingOrError.component.tsx
=> Pass export-status to error QueryPage

src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx
=> Replace "row/column" with "group-by"

src/app/Main/Body/QueryPage/Drawer/Filter/SubFilter-Selector.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent/Parameter/QueryPage-ParameterContent.component.tsx, src/app/Main/Body/QueryPage/Services/ContainerServices/fetchInitialData.service.tsx, src/app/Shared/Model/Client_Isolate.model.ts, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
=> Implement subfilter for AMRs

src/app/Main/Body/QueryPage/Drawer/Filter/SubFilter-Selector.component.tsx, src/app/Main/Body/QueryPage/Services/ExportServices/DataExportServices/generateDataRowsCsvString.service.ts, src/app/Main/Body/QueryPage/Services/ExportServices/dataAndStatisticToZipFile.service.ts, src/app/Shared/Model/Api_Isolate.model.ts, src/app/Shared/Model/Client_Isolate.model.ts, src/app/Shared/adaptIsolatesFromAPI.service.ts
- distinguish between 1/0 and not tested (-)
Ticket: #414
=> Add proper export of AMRs for each isolate

src/app/Main/Body/QueryPage/QueryPage-Layout.component.tsx, src/app/Main/Header/Header.component.tsx, src/app/Main/Main-Layout.component.tsx
=> Change z-index

src/app/Main/Body/InfoPage/Amrs/InfoPage-AmrsDialog.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/FilterDialog/FilterDialog.component.tsx, src/app/Main/Body/QueryPage/ExportDialog/ExportDialog.component.tsx, src/app/Main/Body/QueryPage/Subheader/SubHeader-Button.component.tsx, src/app/Shared/ButtonLabel.component.tsx, src/app/Shared/Dialog.component.tsx
=> Remove Icons form dialog buttons, change color

src/app/Main/Body/QueryPage/Drawer/Drawer-Container.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/Filter-Container.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/Filter-SelectorList.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/SelectorList-Selector.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/SubFilter-Selector.component.tsx, src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent/Parameter/QueryPage-ParameterContent.component.tsx, src/app/Main/Body/QueryPage/Services/ContainerServices/exportZip.service.tsx, src/app/Main/Body/QueryPage/Services/ContainerServices/fetchConditionalFilters.service.tsx, src/app/Main/Body/QueryPage/Services/ContainerServices/fetchInitialData.service.tsx, src/app/Main/Body/QueryPage/Services/ExportServices/generateParameterHeader.service.ts, src/app/Main/Body/QueryPage/Services/PathServices/generatePathString.service.ts, src/app/Main/Body/QueryPage/Services/PathServices/getFilterFromPath.service.ts, src/app/Main/Body/QueryPage/Services/TableServices/generateTableHeaderValues.service.ts, src/app/Main/Body/QueryPage/Services/checkIfFilterIsSet.service.ts, src/app/Main/Body/QueryPage/Services/generateUniqueValues.service.tsx, src/app/Shared/Context/FilterContext.tsx, src/app/Shared/Model/Filter.model.ts
=> Change selected Filter model & remove filterToDisplay

src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx, src/app/Main/Body/QueryPage/Services/ContainerServices/exportZip.service.tsx, src/app/Main/Body/QueryPage/Services/ExportServices/dataAndStatisticToZipFile.service.ts, src/app/Main/Body/QueryPage/Services/ExportServices/generateExportLabels.service.ts, src/app/Main/Body/QueryPage/Services/ExportServices/generateParameterHeader.service.ts, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
=> Add subfilters to the export header

src/app/Main/Body/QueryPage/Drawer/Filter/generateSelectorObject.service.ts, src/app/Main/Body/QueryPage/QueryPageContent/Parameter/QueryPage-ParameterContent.component.tsx, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
=> Replace : in subfilter keys for translation

src/app/Main/Body/QueryPage/QueryPageContent/Results/TableResults/Table/TableMainHeader.component.tsx
=> Add padding to main table header

src/locales/de/InfoPage.json, src/locales/en/InfoPage.json
=> Replace "star" with "*" in table descriptions

src/app/Main/Body/QueryPage/QueryPageContent/NumberOfIsolates/QueryPage-NrOfIsolates.component.tsx, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
- exchange table with grid
Ticket: #455
=> Add information text to NrOfIsolates

src/locales/de/QueryPage.json
=> Change "Subfilter" to "Unterfilter"

src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx
=> Delete Subfilter if not displayed

src/locales/de/ExampleQueries.json, src/locales/en/ExampleQueries.json, src/locales/en/Header.json
=> Add english translation to ExampleQueries

src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx
=> Only set new subfilter if not already set

src/locales/de/InfoPage.json, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
=> Editing text and translation

src/app/Main/Body/QueryPage/ExportDialog/ExportDialog-Checkboxes.component.tsx, src/app/Main/Body/QueryPage/ExportDialog/ExportDialog.component.tsx, src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx, src/app/Shared/Checkboxes.component.tsx, src/locales/de/Export.json, src/locales/en/Export.json, src/locales/en/QueryPage.json
=> Disable Checkboxes, add warning

src/app/Main/Body/QueryPage/Services/ContainerServices/exportZip.service.tsx, src/app/Main/Body/QueryPage/Services/ExportServices/DataExportServices/generateDataRowsCsvString.service.ts, src/app/Main/Body/QueryPage/Services/ExportServices/DataExportServices/generateDataTableCsvString.service.ts, src/app/Main/Body/QueryPage/Services/ExportServices/adaptApiIsolates.service.ts, src/app/Main/Body/QueryPage/Services/ExportServices/dataAndStatisticToZipFile.service.ts, src/app/Main/Body/QueryPage/Services/ExportServices/generateExportLabels.service.ts, src/app/Shared/Model/Api_Isolate.model.ts, src/app/Shared/Model/Client_Isolate.model.ts, src/app/Shared/adaptIsolatesFromAPI.service.ts, src/locales/de/QueryPage.json, src/locales/en/QueryPage.json
=> Integrate subFilters in isolates export table

src/app/Main/Body/InfoPage/Amrs/InfoPage-AmrsDialog.component.tsx, src/app/Main/Body/InfoPage/AmrsTables.constants.tsx, src/app/Main/Body/InfoPage/InfoPage-Container.component.tsx, src/app/Main/Body/InfoPage/InfoPage.model.tsx, src/locales/de/InfoPage.json, src/locales/en/InfoPage.json
=> Add abbr. to info tables

src/app/Main/Body/QueryPage/QueryPageContent/NumberOfIsolates/QueryPage-NrOfIsolates.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent/QueryPageContent-Container.tsx
=> Only show selected nr if filter is selected

src/app/Main/Body/InfoPage/InfoPage-Container.component.tsx
=> Add comma to separate header cells

src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent/QueryPageContent-Container.tsx, src/app/Main/Body/QueryPage/QueryPageContent/Results/Charts/ApexChart.model.ts, src/app/Main/Body/QueryPage/QueryPageContent/Results/Charts/BarChartResults.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent/Results/Charts/ChartWithSubCharts.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent/Results/Charts/QueryPageBarChart-Container.tsx, src/app/Main/Body/QueryPage/QueryPageContent/Results/Charts/processingTableDataToApexData.service.tsx, src/app/Shared/Context/DataContext.tsx
=> Add Chart for each SubTable

src/app/Main/Body/QueryPage/ExampleQueriesDialog/ExampleQueries.constants.ts
=> Exchange wrong example query URL for MRSA

package-lock.json, src/app/Main/Body/QueryPage/Drawer/Filter/SelectorList-Selector.component.tsx, src/app/Main/Body/QueryPage/Drawer/Filter/SubFilter-Selector.component.tsx, src/app/Main/Body/QueryPage/Services/checkIfFilterIsSet.service.ts
=> Adapt CheckIfSingleFilterIsSetService to SubFilter

src/app/Main/Body/QueryPage/QueryPageContent/Results/TableResults/TableResults-Container.component.tsx
=> Add relative data to subTables

src/app/Main/Body/LinkPage/LinkPage.component.tsx
- remove "emotion" package
Ticket: #507
=> Use material-ui sx styling

src/app/Main/Body/LinkPage/LinkPage.component.tsx
=> Use theme for header color

src/app/Main/Body/InfoPage/Amrs/InfoPage-AmrsContent.component.tsx
=> Use Theme for Divider

src/app/Main/Body/InfoPage/InfoPage.component.tsx
=> Add line same line height to background text

src/app/Main/Body/DataProtectionPage/DataProtectionPage.component.tsx
=> Use only material ui styling for DataProtectionPage

src/app/Main/Body/QueryPage/QueryPage-Container.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent/Results/Charts/ChartWithSubCharts.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent/Results/Charts/QueryPageBarChart-Container.tsx, src/app/Main/Body/QueryPage/QueryPageContent/Results/TableResults/Table/createTableRows.service.tsx, src/app/Shared/Model/Client_Isolate.model.ts
=> Display subTables for "matrixDetail"

src/locales/en/HomePage.json
=> Exchange text on HomePage

src/app/Main/Body/QueryPage/ExportDialog/ExportDialog.component.tsx
=> Remove "emotion" styling from ExportDialog

src/app/Main/Body/EvaluationsPage/EvaluationPage-Card.component.tsx, src/app/Main/Body/EvaluationsPage/EvaluationPage-NavButtons.component.tsx, src/app/Main/Body/EvaluationsPage/EvaluationPage.component.tsx, src/app/Main/Body/InfoPage/InfoPage.component.tsx
- Adapt Style of InfoPage
Ticket: #530
=> Remove "emotion" from EvaluationPage

src/app/Main/Body/QueryPage/QueryPageContent/DatabaseStatusIndicator/QueryPage-DatabaseStatusIndicator.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent/IntroText/QueryPage-IntroText.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent/NumberOfIsolates/QueryPage-NrOfIsolates.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent/QueryPageContent-Layout.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent/Results/Charts/ChartWithSubCharts.component.tsx, src/app/Main/Body/QueryPage/QueryPageContent/Results/Charts/QueryPageBarChart-Container.tsx, src/app/Main/Body/QueryPage/QueryPageContent/Results/TableResults/TableResults-Options.component.tsx
=> Remove "emotion" from QueryPageContent except table

src/app/Shared/Model/Api_Info.model.ts, src/app/Shared/Model/CMS.model.ts, src/app/Shared/components/footer/Footer-Container.component.tsx, src/app/Shared/infrastructure/router/routes.ts, src/app/evaluations/model/Evaluations.model.ts, src/app/evaluations/pages/evaluationsUseCases.ts, src/app/welcome/pages/welcomeUseCase.ts, src/locales/de/DataProtection.json, src/locales/en/DataProtection.json
=> Remove faulty info request from frontend

package-lock.json, package.json, src/app/evaluations/components/EvaluationCardComponent.tsx
=> Add Markdown rendering to lte card

src/app/evaluations/model/Evaluations.model.ts, src/app/evaluations/pages/evaluationsUseCases.ts, src/locales/de/ExplanationPage.json, src/locales/en/ExplanationPage.json
Fix translation typo for Masthaehnchen
Remove translations for Weiter Details
Add translation for Diverse and Multiple
Ticket: #572
=> Remove filter options for weitere details

src/locales/de/ExplanationPage.json, src/locales/de/Header.json, src/locales/en/ExplanationPage.json, src/locales/en/Header.json
=> Change Langzeitauswertung translation to Auswertung

.env.development, .env.production, .env.qa
=> Amend dot env files to point to proper server address'

src/app/pages/explanation/Amrs/InfoPage-AmrsContent.component.tsx, src/app/pages/explanation/InfoPage-Container.component.tsx
Error was coming because we had P element inside another P element. Used <> instead of <p> with some styling on the Typography component
closes #587
=> Changed HTML element structure

src/app/evaluations/model/Evaluations.model.ts, src/app/evaluations/pages/evaluationsUseCases.ts
=> Add 'Multiple' Division Section and Option

src/app/pages/links/LinkList-ListContent.component.tsx, src/app/pages/links/LinkPage-LinkList.component.tsx
Fixed  #586
By adding "key" which makes each element inside iterator unique
=> Fix for react error on External links page #586

.github/workflows/deploy-on-qa.yml
#571 Adding artifact to workflow
=> Adding artifact to workflow

.github/workflows/deploy-on-qa.yml
Updated yml to send commit$, current datetime #609
=> Updated yml to send commit$, current datetime #609

.github/workflows/deploy-on-qa.yml
Used a package inside workflow to get a substring from the full SHA of the commit
=> Corrected command to get short SHA of commit #612

src/app/shared/components/footer/LastUpdate.component.tsx, src/app/shared/infrastructure/api/callApi.service.ts
Read cms-version header from API response and display it on the UI #608
=> Read cms-version header from API response

src/app/evaluations/pages/evaluationsUseCases.ts, src/locales/de/InfoPage.json
=> Fix deselection of all filter values returning all results

src/app/evaluations/components/EvaluationCardComponent.tsx
=> Adjust image viewer image size

src/app/explanation/components/ExplanationTermComponent copy.tsx, src/app/shared/components/footer/Footer-LinkList.component.tsx, src/app/shared/components/header/Header.component.tsx, src/app/shared/style/Style-MainTheme.ts, src/assets/styles.css, src/index.html
=> Change Color Scheme and Font to match new BfR Corporate Design templatei

src/app/shared/components/logo_card/Logo.component.tsx, src/app/shared/components/logo_card/LogoCard.component.tsx, src/locales/de/HomePage.json, src/locales/en/HomePage.json
=> Change BfR Logo component

src/app/shared/components/footer/Footer-LinkList.component.tsx
=> Make link to BfR Homepage dependent on locale

src/app/evaluations/components/EvaluationCardComponent.tsx
Button Styling:
Inside the sx prop of the Button, you've specified styles that use the @media queries. These media queries change the font size of the text inside the button based on the viewport width:                                                                                                       
"@media (max-width: 450px)": {
fontSize: "0.7em",
},
"@media (max-width: 350px)": {
fontSize: "0.6em",
},
=> solving text overflow

.env, package-lock.json, package.json, src/app/evaluations/pages/EvaluationsMainComponent.tsx, src/locales/de/ExplanationPage.json, src/locales/en/ExplanationPage.json
=> Moved filters to a sidebar #649

package-lock.json, package.json, src/app/evaluations/components/FilterMultiSelectionComponent.tsx, src/app/evaluations/utils/utils.ts, src/locales/de/ExplanationPage.json, src/locales/en/ExplanationPage.json
=> Add "Select All" which allows select/deselect all operation on each dropdown 

src/app/evaluations/pages/EvaluationsMainComponent.tsx
Hide filter tags for this release
closes #663
=> Hide filter tags for this release #663

src/app/evaluations/pages/evaluationsUseCases.ts, src/locales/de/ExplanationPage.json, src/locales/en/ExplanationPage.json
=> Fix ESBL_AMPC_E_COLI microorganism token spelling

src/app/evaluations/pages/evaluationsUseCases.ts, src/locales/de/ExplanationPage.json, src/locales/en/ExplanationPage.json
Remove Hihn and Pute from production type
Ticket: cms#59
=> Add Mastrund to Production Type

src/app/shared/components/header/Header.component.tsx
removed border from the header
=> #669 removed border from the header

src/app/evaluations/components/EvaluationDivisionData.tsx, src/app/evaluations/components/FilterContainerComponent.tsx, src/app/evaluations/pages/EvaluationsMainComponent.tsx, src/app/evaluations/pages/evaluationsUseCases.ts, src/locales/de/ExplanationPage.json, src/locales/en/ExplanationPage.json
Show no records found msg on a division of explanation page
=> #667 Show no records found msg

src/app/evaluations/pages/evaluationsUseCases.ts
This update code snippet replaced existing fetchData function within the useEvaluationPageComponent hook. It takes the response.data.data array, sorts it by the title attribute , and then processes the entries as before.
=> #629 -sorting data in evaluation page(alphabetically)

src/app/evaluations/components/EvaluationCardComponent.tsx, src/app/evaluations/pages/EvaluationsMainComponent.tsx, src/app/shared/components/footer/Footer-Layout.component.tsx, src/app/shared/components/header/Header.component.tsx, src/app/shared/style/Style-MainTheme.ts
Configured header, footer height from settings. Used same to calculate dynamic height for the ImageViewer.
=> 659 css issue graph

src/app/evaluations/pages/EvaluationsMainComponent.tsx, src/app/evaluations/pages/evaluationsUseCases.ts, src/locales/de/ExplanationPage.json, src/locales/en/ExplanationPage.json, src/locales/en/HomePage.json
=> Change Evaluation page how to Card to collapsable accordion

src/app/evaluations/components/FilterContainerComponent.tsx, src/app/evaluations/pages/EvaluationsMainComponent.tsx
=> Move Evaluation page how to into sidebar

webpack.config.js
change client version to 1.0.0
=> 699 change client version

src/app/ld/components/FilterContainerComponent.tsx, src/app/ld/model/LinkedData.model.ts, src/app/ld/pages/LinkedDataUseCases.ts, src/locales/de/ExplanationPage.json, src/locales/en/ExplanationPage.json
=> Renamed "Upper Category" to "Top Category"

src/app/ld/components/JSONViewerComponent.tsx, src/app/ld/pages/LinkedDataComponent.tsx, src/app/ld/pages/LinkedDataUseCases.ts
default filters are now blank on LD to reduce API failures
=> 726 ld no default selection on the filters

src/app/App.tsx
Changed position of the mobile view msg.
There seems problem with the width of the alert when I check it in developer's mode.
But first we should deploy and check if there is any such problem on actual mobile.
=> positioning of the mobile view msg fixed

src/app/shared/components/footer/Footer-LinkList.component.tsx, src/app/shared/infrastructure/router/routes.ts
=> Add API-Doc link to footer

src/locales/de/ExplanationPage.json, src/locales/en/ExplanationPage.json
update Listeria Monocytogenes to Listeria monocytogenes
=> change text: Listeria Monocytogenes to Listeris monocytogenes

src/app/prevalence/components/PrevalenceSideContent.tsx, src/app/prevalence/pages/prevalenceUseCases.ts, src/locales/de/PrevalencePage.json, src/locales/en/PrevalencePage.json
=> Change Filter to Search on Prevalence Side Panel

src/app/prevalence/components/PrevalenceDataContext.tsx, src/app/prevalence/components/PrevalenceDataGrid.tsx, src/locales/de/PrevalencePage.json, src/locales/en/PrevalencePage.json
=> Adjust columns in prevalence data table

src/app/shared/infrastructure/router/routes.ts
=> Update API documentation endpoint

src/app/evaluations/components/FilterMultiSelectionComponent.tsx, src/app/prevalence/components/PrevalenceSideContent.tsx
=> part of some words of microorganism change to italic

.github/workflows/deploy-on-qa.yml
=> Add waorkflow-dispatch trigger to deploy-on-QA workflow

.github/workflows/deploy-on-prod.yml
=> Add github action to deploy to production server

.github/workflows/build_test_pr.yml, .github/workflows/deploy-on-qa.yml
=> Add automatic build upon pull request creation

.github/workflows/build_test_pr.yml
=> Add  linting to PR CI

.github/workflows/deploy-on-prod.yml
=> Fix deploy to production

src/app/prevalence/components/PrevalenceDataContext.tsx
=> selection order of the filter dropdowns to affect the filter options available

src/app/prevalence/components/PrevalenceDataGrid.tsx, src/app/prevalence/components/PrevalenceSideContent.tsx
…tors and different decimal formats for dot and comma
=> Update PrevalenceDataGrid to generate CSV files with semicolon separators and different decimal formats for dot and comma

src/app/prevalence/components/PrevalenceChart.tsx
=> The X-axis should only have 2 allowed Maximum values: either 25% (vor Values + CI below 25%) or 100% for all the other

src/app/prevalence/components/PrevalenceChart.tsx
additionally I changed background color for chart image t when user download it (dark to light)
=> Bug fixed_ download individual chart
